### ISSUE TITLE
Slider navigation button color and position mismatch on SpecialOffers section

### ISSUE THREAD

**Issue by Izzatillo075** [byStrange/kia.uz-frontend#56] opened 2024-11-18 17:57 UTC
![image](https://github.com/user-attachments/assets/9f966c51-8e97-400f-b5a2-8dab8ec0b580)
![image](https://github.com/user-attachments/assets/1b0322e2-a07d-4a63-90df-153d386db33b)
   Icon position and color is different from design

**Comment by byStrange** [comment] 2024-11-19 11:25
duplicate of #55. And icon position depends on the content height so it would not really be issue since content is dynamic and could change.

**Closed by byStrange** 2024-11-19 11:25 UTC
Labels: duplicate, good first issue
